### PR TITLE
Added GitTest2

### PR DESCRIPTION
**Pull request by mini1985**
Code committed and send for review

Regards,
mini

### CODE REVIEW

**Comment by wilfeevans** [comment]
hi,
The code looks good do some changes for subtraction also

**Comment by mini1985** [comment]
Changes committed please review

**Comment by mini1985** [comment]
Please review

**Comment by mini1985** [comment]
please review the update

**Comment by wilfeevans** [comment]
go ahead and merge

**Comment by mini1985** [comment]
merged successfully

**Pull request merged**
